// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/maanasasubrahmanyam-sd/customeValTest/interfaces/test_server/test.proto

package test_server

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "./validator"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	regexp "regexp"
	github_com_arkadyb_go_proto_validators "github.com/arkadyb/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var _regex_SearchRequest_Name = regexp.MustCompile(`maanasa`)

func (this *SearchRequest) Validate() error {
	if !_regex_SearchRequest_Name.MatchString(this.Name) {
		return github_com_arkadyb_go_proto_validators.FieldError("Name", fmt.Errorf(`value '%v' must be a string conforming to regex "maanasa"`, this.Name))
	}
	return nil
}
func (this *SearchResponse) Validate() error {
	return nil
}
